"""Reusable single-property accessibility scoring service.

Runs locally with SQLite by default. When DATABASE_URL is configured, it uses
Supabase Postgres for shared online persistence instead.
"""
from __future__ import annotations

import bisect
import csv
import hashlib
import json
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row

from accessibility_poc import (
    ROOT, build_network, fetch_overpass, nearest_road, overpass_query,
    parse_width_m, score_property, vehicle_access_score_v3,
)

LOCAL_DATABASE_PATH = ROOT / "data" / "accessibility_service.sqlite3"
LOCAL_RAW_CACHE_DIR = ROOT / "data" / "ui_raw_cache"
V3_REFERENCE_OUTPUT = ROOT / "data" / "output" / "accessibility_poc_20260722T062125Z_v3.csv"
V3_BETA_REFERENCE = ROOT / "reference_data" / "v3_beta_reference.json"


def load_config() -> dict[str, Any]:
    return json.loads((ROOT / "config.json").read_text(encoding="utf-8"))


def database_url() -> str | None:
    """Return the optional hosted-database URL without requiring it locally."""
    value = os.environ.get("DATABASE_URL")
    if value:
        return value
    try:
        import streamlit as st

        value = st.secrets.get("DATABASE_URL")
        if value:
            return str(value)
    except Exception:
        pass
    return None


def is_postgres(connection: Any) -> bool:
    return isinstance(connection, psycopg.Connection)


def connect() -> sqlite3.Connection | psycopg.Connection:
    url = database_url()
    if url:
        connection = psycopg.connect(url, row_factory=dict_row, connect_timeout=10)
        with connection.cursor() as cursor:
            cursor.execute("""CREATE TABLE IF NOT EXISTS raw_cache (
                cache_key TEXT PRIMARY KEY,
                response_json TEXT NOT NULL,
                fetched_at TIMESTAMPTZ NOT NULL
            )""")
            cursor.execute("""CREATE TABLE IF NOT EXISTS assessments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                property_code TEXT NOT NULL,
                latitude DOUBLE PRECISION NOT NULL,
                longitude DOUBLE PRECISION NOT NULL,
                connectivity_weight DOUBLE PRECISION NOT NULL,
                road_width_weight DOUBLE PRECISION NOT NULL,
                source TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL,
                result_json TEXT NOT NULL
            )""")
        connection.commit()
        return connection

    LOCAL_DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(LOCAL_DATABASE_PATH)
    connection.row_factory = sqlite3.Row
    connection.execute("""CREATE TABLE IF NOT EXISTS raw_cache (
        cache_key TEXT PRIMARY KEY, response_json TEXT NOT NULL, fetched_at TEXT NOT NULL
    )""")
    connection.execute("""CREATE TABLE IF NOT EXISTS assessments (
        id INTEGER PRIMARY KEY AUTOINCREMENT, property_code TEXT NOT NULL, latitude REAL NOT NULL,
        longitude REAL NOT NULL, connectivity_weight REAL NOT NULL, road_width_weight REAL NOT NULL,
        source TEXT NOT NULL, created_at TEXT NOT NULL, result_json TEXT NOT NULL
    )""")
    connection.commit()
    return connection


def raw_cache_key(latitude: float, longitude: float, config: dict[str, Any]) -> str:
    value = f"{latitude:.7f}|{longitude:.7f}|{config['road_radius_m']}|{config['poi_radius_m']}"
    return hashlib.sha256(value.encode()).hexdigest()[:24]


def accessibility_score_v2(
    connectivity_score: float | None,
    vehicle_access_score: float | None,
    connectivity_weight: float,
    vehicle_access_weight: float,
) -> float | None:
    """Calculate v2 from connectivity and vehicle access only."""
    if connectivity_score is None or vehicle_access_score is None:
        return None
    total_weight = connectivity_weight + vehicle_access_weight
    if total_weight <= 0:
        return None
    return round(
        (connectivity_score * connectivity_weight + vehicle_access_score * vehicle_access_weight) / total_weight,
        1,
    )


def national_beta_percentile(beta: float) -> float:
    """Use the completed V3 population as the reference for a new property's beta."""
    if V3_REFERENCE_OUTPUT.exists():
        with V3_REFERENCE_OUTPUT.open(newline="", encoding="utf-8-sig") as stream:
            values = sorted(
                float(row["beta"])
                for row in csv.DictReader(stream)
                if row.get("beta") not in (None, "")
            )
    elif V3_BETA_REFERENCE.exists():
        values = json.loads(V3_BETA_REFERENCE.read_text(encoding="utf-8"))["beta_values"]
    else:
        return 50.0
    left, right = bisect.bisect_left(values, beta), bisect.bisect_right(values, beta)
    return 100 * ((left + right) / 2) / len(values) if values else 50.0


def accessibility_v3_for_new_property(
    row: dict[str, Any], raw_data: dict[str, Any], config: dict[str, Any]
) -> dict[str, Any]:
    """Score a new coordinate with the national V3 connectivity reference.

    The form does not collect a city, so city percentiles are intentionally not
    used for individual assessments.
    """
    elements = raw_data.get("elements", [])
    nodes, roads, _ = build_network(elements)
    nearest, distance = nearest_road(float(row["LATITUDE"]), float(row["LONGITUDE"]), roads, nodes)
    tags = nearest.get("tags", {}) if nearest else {}
    width, _ = parse_width_m(tags, config["road_width_fallback_m"])
    vehicle, hard_blocked = vehicle_access_score_v3(
        tags, width, distance, config["score_thresholds"], nearest is not None
    )
    beta = row.get("beta")
    confidence = row.get("data_confidence_score")
    if beta is None or confidence is None:
        return {
            "vehicle_access_score_v3": vehicle,
            "connectivity_score_v3": None,
            "base_accessibility_score_v3": None,
            "overall_accessibility_score_v3": None,
            "accessibility_status_v3": "Insufficient data",
            "connectivity_reference_v3": "national",
        }
    connectivity = national_beta_percentile(float(beta))
    base = 0.60 * vehicle + 0.40 * connectivity
    adjusted = base * (0.85 + 0.15 * float(confidence) / 100)
    if hard_blocked:
        overall, status = 0.0, "Blocked"
    elif vehicle < 25:
        overall, status = min(adjusted, 35), "Manual review"
    elif vehicle < 50:
        overall, status = min(adjusted, 60), "Review access"
    else:
        overall, status = adjusted, "Good"
    return {
        "vehicle_access_score_v3": round(vehicle, 1),
        "connectivity_score_v3": round(connectivity, 1),
        "base_accessibility_score_v3": round(base, 1),
        "overall_accessibility_score_v3": round(overall, 1),
        "accessibility_status_v3": status,
        "connectivity_reference_v3": "national",
    }


def get_raw_data(
    connection: sqlite3.Connection | psycopg.Connection,
    latitude: float,
    longitude: float,
    config: dict[str, Any],
) -> tuple[dict[str, Any], str]:
    key = raw_cache_key(latitude, longitude, config)
    if is_postgres(connection):
        with connection.cursor() as cursor:
            cursor.execute("SELECT response_json FROM raw_cache WHERE cache_key = %s", (key,))
            cached = cursor.fetchone()
        if cached:
            return json.loads(cached["response_json"]), "Supabase cache"
        data = fetch_overpass(
            overpass_query(latitude, longitude, config["road_radius_m"], config["poi_radius_m"]),
            config,
            None,
        )
        with connection.cursor() as cursor:
            cursor.execute(
                """INSERT INTO raw_cache (cache_key, response_json, fetched_at)
                   VALUES (%s, %s, %s)
                   ON CONFLICT (cache_key) DO UPDATE
                   SET response_json = EXCLUDED.response_json, fetched_at = EXCLUDED.fetched_at""",
                (key, json.dumps(data), datetime.now(timezone.utc)),
            )
        connection.commit()
        return data, "Public Overpass"

    cached = connection.execute("SELECT response_json FROM raw_cache WHERE cache_key = ?", (key,)).fetchone()
    if cached:
        return json.loads(cached["response_json"]), "SQLite cache"
    LOCAL_RAW_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    file_cache = LOCAL_RAW_CACHE_DIR / f"{key}.json"
    existed = file_cache.exists()
    data = fetch_overpass(
        overpass_query(latitude, longitude, config["road_radius_m"], config["poi_radius_m"]),
        config,
        file_cache,
    )
    connection.execute(
        "INSERT OR REPLACE INTO raw_cache VALUES (?, ?, ?)",
        (key, json.dumps(data), datetime.now(timezone.utc).isoformat()),
    )
    connection.commit()
    return data, "Local file cache" if existed else "Public Overpass"


def assess_property(
    property_code: str,
    latitude: float,
    longitude: float,
    connectivity_weight: float = 50.0,
    vehicle_access_weight: float = 50.0,
) -> dict[str, Any]:
    if connectivity_weight < 0 or vehicle_access_weight < 0 or connectivity_weight + vehicle_access_weight <= 0:
        raise ValueError("At least one positive weight is required.")
    config = load_config()
    # Retained only to calculate and store the legacy V2 comparison field.
    config["initial_weights"] = {"connectivity": 50.0, "road_width": 50.0}
    connection = connect()
    try:
        raw_data, source = get_raw_data(connection, latitude, longitude, config)
        result = score_property(
            {"PROPERTY_CODE": property_code, "LATITUDE": str(latitude), "LONGITUDE": str(longitude), "CITY": ""},
            raw_data,
            config,
        )
        result["overall_accessibility_score_v2"] = accessibility_score_v2(
            result.get("connectivity_score"),
            result.get("vehicle_access_score"),
            connectivity_weight,
            vehicle_access_weight,
        )
        result.update(accessibility_v3_for_new_property(result, raw_data, config))
        result.update(
            {
                "scoring_model_version": "v3",
                "connectivity_weight": connectivity_weight,
                "vehicle_access_weight": vehicle_access_weight,
                "data_source": source,
                "created_at": datetime.now(timezone.utc).isoformat(),
                "processing_status": "scored",
                "error_message": "",
            }
        )
        values = (
            property_code,
            latitude,
            longitude,
            connectivity_weight,
            vehicle_access_weight,
            source,
            result["created_at"],
            json.dumps(result),
        )
        if is_postgres(connection):
            with connection.cursor() as cursor:
                cursor.execute(
                    """INSERT INTO assessments
                       (property_code, latitude, longitude, connectivity_weight, road_width_weight, source, created_at, result_json)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                    values,
                )
        else:
            connection.execute(
                """INSERT INTO assessments
                   (property_code, latitude, longitude, connectivity_weight, road_width_weight, source, created_at, result_json)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                values,
            )
        connection.commit()
        return result
    finally:
        connection.close()


def recent_assessments(limit: int = 200) -> list[dict[str, Any]]:
    connection = connect()
    try:
        if is_postgres(connection):
            with connection.cursor() as cursor:
                cursor.execute("SELECT result_json FROM assessments ORDER BY id DESC LIMIT %s", (limit,))
                rows = cursor.fetchall()
        else:
            rows = connection.execute("SELECT result_json FROM assessments ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
        return [json.loads(row["result_json"]) for row in rows]
    finally:
        connection.close()
