"""Reusable single-property accessibility scoring service with Supabase Postgres persistence."""
from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from typing import Any

import psycopg
from psycopg.rows import dict_row

from accessibility_poc import ROOT, fetch_overpass, overpass_query, score_property


def load_config() -> dict[str, Any]:
    return json.loads((ROOT / "config.json").read_text(encoding="utf-8"))


def database_url() -> str:
    """Read the secret only from the runtime environment or Streamlit secrets."""
    value = os.environ.get("DATABASE_URL")
    if value:
        return value
    try:
        import streamlit as st

        value = st.secrets.get("DATABASE_URL")
        if value:
            return str(value)
    except Exception:
        pass
    raise RuntimeError(
        "DATABASE_URL is not configured. Add it to .streamlit/secrets.toml locally "
        "or to the Streamlit Cloud Secrets settings."
    )


def connect() -> psycopg.Connection:
    connection = psycopg.connect(database_url(), row_factory=dict_row, connect_timeout=10)
    with connection.cursor() as cursor:
        cursor.execute("""CREATE TABLE IF NOT EXISTS raw_cache (
            cache_key TEXT PRIMARY KEY,
            response_json TEXT NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL
        )""")
        cursor.execute("""CREATE TABLE IF NOT EXISTS assessments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_code TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            connectivity_weight DOUBLE PRECISION NOT NULL,
            road_width_weight DOUBLE PRECISION NOT NULL,
            source TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            result_json TEXT NOT NULL
        )""")
    connection.commit()
    return connection


def raw_cache_key(latitude: float, longitude: float, config: dict[str, Any]) -> str:
    value = f"{latitude:.7f}|{longitude:.7f}|{config['road_radius_m']}|{config['poi_radius_m']}"
    return hashlib.sha256(value.encode()).hexdigest()[:24]


def get_raw_data(
    connection: psycopg.Connection, latitude: float, longitude: float, config: dict[str, Any]
) -> tuple[dict[str, Any], str]:
    key = raw_cache_key(latitude, longitude, config)
    with connection.cursor() as cursor:
        cursor.execute("SELECT response_json FROM raw_cache WHERE cache_key = %s", (key,))
        cached = cursor.fetchone()
    if cached:
        return json.loads(cached["response_json"]), "Supabase cache"

    data = fetch_overpass(
        overpass_query(latitude, longitude, config["road_radius_m"], config["poi_radius_m"]),
        config,
        None,
    )
    with connection.cursor() as cursor:
        cursor.execute(
            """INSERT INTO raw_cache (cache_key, response_json, fetched_at)
               VALUES (%s, %s, %s)
               ON CONFLICT (cache_key) DO UPDATE
               SET response_json = EXCLUDED.response_json, fetched_at = EXCLUDED.fetched_at""",
            (key, json.dumps(data), datetime.now(timezone.utc)),
        )
    connection.commit()
    return data, "Public Overpass"


def assess_property(
    property_code: str,
    latitude: float,
    longitude: float,
    connectivity_weight: float,
    road_width_weight: float,
) -> dict[str, Any]:
    if connectivity_weight < 0 or road_width_weight < 0 or connectivity_weight + road_width_weight <= 0:
        raise ValueError("At least one positive weight is required.")
    config = load_config()
    config["initial_weights"] = {"connectivity": connectivity_weight, "road_width": road_width_weight}
    connection = connect()
    try:
        raw_data, source = get_raw_data(connection, latitude, longitude, config)
        result = score_property(
            {"PROPERTY_CODE": property_code, "LATITUDE": str(latitude), "LONGITUDE": str(longitude), "CITY": ""},
            raw_data,
            config,
        )
        result.update(
            {
                "connectivity_weight": connectivity_weight,
                "road_width_weight": road_width_weight,
                "data_source": source,
                "created_at": datetime.now(timezone.utc).isoformat(),
                "processing_status": "scored",
                "error_message": "",
            }
        )
        with connection.cursor() as cursor:
            cursor.execute(
                """INSERT INTO assessments
                   (property_code, latitude, longitude, connectivity_weight, road_width_weight, source, created_at, result_json)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (
                    property_code,
                    latitude,
                    longitude,
                    connectivity_weight,
                    road_width_weight,
                    source,
                    result["created_at"],
                    json.dumps(result),
                ),
            )
        connection.commit()
        return result
    finally:
        connection.close()


def recent_assessments(limit: int = 200) -> list[dict[str, Any]]:
    connection = connect()
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT result_json FROM assessments ORDER BY id DESC LIMIT %s", (limit,))
            rows = cursor.fetchall()
        return [json.loads(row["result_json"]) for row in rows]
    finally:
        connection.close()
